name: Go
on: [push, pull_request]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.15
      uses: actions/setup-go@v2
      with:
        go-version: 1.15
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      run: go build -v .

  docker:
    name: Docker
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: docker build
      run: docker build -t mattn/longcat .

    - name: check image size
      run: docker images | grep longcat

    - name: check run
      run: docker run --rm mattn/longcat
